import Head from "next/head";
import Feed from "../components/Feed";
import Widgets from "../components/Widgets";
import { useSession, getProviders, getSession } from "next-auth/react";
import Login from "../components/Login";
import Modal from "../components/Modal";
import { modalState } from "../atoms/modalAtom";
import { useRecoilState } from "recoil";


export default function Home({ trending, following, providers }) {
  const [isOpen, setIsOpen] = useRecoilState(modalState);

  const { data: session } = useSession();

  if (!session) return <Login providers={providers} />;

  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Feed />
      <Widgets />
      {isOpen && <Modal />}
    </>
  );
}

export async function getServerSideProps(context) {
  const trending = await fetch("https://jsonkeeper.com/b/NKEV").then((res) =>
    res.json()
  );
  const following = await fetch("https://jsonkeeper.com/b/WWMJ").then((res) =>
    res.json()
  );

  const providers = await getProviders();
  const session = await getSession(context); // get session on the server side to prevent flickering

  return {
    props: {
      trending,
      following,
      session,
      providers,
    },
  };
}
